
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Toaster } from 'react-hot-toast';

import StoreProvider from "./StoreProvider";
import AuthInitializer from './AuthInitializer'

import LayoutWrapper from "../components/LayoutWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body

        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>

          <div className="flex flex-col min-h-screen">
            <LayoutWrapper>
              <AuthInitializer />

              <div className="flex-1">
                {children}

                <Toaster />
              </div>
            </LayoutWrapper>
          </div>
        </ StoreProvider>
      </body>
    </html>
  );
}
